package nerdle;

import org.junit.jupiter.api.RepeatedTest;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class FunctionsTest {
    Functions functions = new Functions();

    //test for the method that checks whether input equation is valid or not
    @Test
    void isValidEq() {
        assertFalse(functions.isValidEq("02+1324"));        //no "="
        assertFalse(functions.isValidEq("243=243"));        //no operation
        assertFalse(functions.isValidEq("1+2-3*4=0"));        //3 operations
        assertFalse(functions.isValidEq("02+"));        //too short
        assertFalse(functions.isValidEq("65/5=14"));        //not equal
        assertFalse(functions.isValidEq("0 2+13  = 15"));        //empty spaces
        assertTrue(functions.isValidEq("12/3+2=6"));     //proper eq
        assertTrue(functions.isValidEq(functions.generateEquation()));         //equation generated by generateEquation method
    }

    //test for the method that generates equation
    //it repeats 15 times
    @RepeatedTest(15)
    @org.junit.jupiter.api.Test
    void generateEquation() {
        assertTrue(functions.generateEquation().contains("="));
        assertTrue(functions.isValidEq(functions.generateEquation()));
    }
}